
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, World!
  displayName: 'Run a one-line script'

- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    codeCoverageToolOption: JaCoCo

- task: CopyFiles@2
  displayName: 'Copy Files to $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    preserveTimestamp: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish and Build'
  inputs:
     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
     ArtifactName: 'drop'
     publishLocation: 'Container'
     