
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, World!
  displayName: 'Run a one-line script'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: NexusIqPipelineTask@1
  inputs:
    nexusIqService: 'Nexus IQ'
    applicationId: 'myapp'
    stage: 'Build'
    ignoreSystemError: true
    javaSystemProperties: '-Djava.net.useSystemProxies=false' 