# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default


steps:
- script: echo Hello, World!
- script: mkdir veracode_upload && zip -r $(Build.SourcesDirectory)/veracode_upload/$(build.buildNumber).zip $(Build.SourcesDirectory) -x */.git/* *.go
  displayName: 'Run a one-line script'
- script: env | sort
- script: set XDG_CONFIG_HOME=/ # outputs secondValue
- script: echo ${XDG_CONFIG_HOME} # outputs secondValue
  
- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    codeCoverageToolOption: JaCoCo

- task: CopyFiles@2
  displayName: 'Copy Files to $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    preserveTimestamp: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish and Build'
  inputs:
     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
     ArtifactName: 'drop'
     publishLocation: 'Container'
- task: NexusIqPipelineTask@1
  inputs:
    nexusIqService: 'Nexus IQ'
    applicationId: 'myapp'
    stage: 'Build'
    ignoreSystemError: true
    failOnStderr: false