# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- script:  mkdir veracode_upload && zip -r $(Build.SourcesDirectory)/veracode_upload/$(build.buildNumber).zip $(Build.SourcesDirectory) -x */.git/* *.go
  displayName: Archive Source for ScansX
  failOnStderr: true


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'
      
- task: NexusIqPipelineTask@1
  displayName: Run Nexus IQ Scan
  env:
    XDG_CONFIG_HOME: ''
  inputs:
    nexusIqService: 'Nexus IQ'
    applicationId: 'myapp'
    stage: 'Build'
    scanTargets: '**/*.jar, **/*.war, **/*.ear, **/*.zip, **/*.tar.gz, **/*.tgz' 
    ignoreSystemError: false
    javaSystemProperties: '-Djava.net.useSystemProxies=false -Dhttp.proxyHost=myproxy -Dhttp.proxyPort=8080'
    
- task: NexusIqPipelineTask@1
  inputs:
    nexusIqService: 'Nexus IQ'
    applicationId: 'myapp'
    stage: 'Build'
    javaSystemProperties: '-Djava.net.useSystemProxies=false -Dhttp.proxyHost=myproxy -Dhttp.proxyPort=8080'

